p8105\_hw5\_zw2541
================
Zixu\_Wang
11/4/2018

Problem 1
---------

### Read and clean the data

Create a tidy dataframe containing data from all participants, including the subject ID, arm, and observations over time.

``` r
file_names = list.files(path = "./data_1")


read_and_tidy = function(file_names){
   a = read.csv(str_c("./data_1/", file_names)) %>% 
     janitor::clean_names() %>% 
     as.data.frame() %>% 
     mutate(group = file_names) %>% 
     select(group, everything())
}

study_data = map(file_names, read_and_tidy) %>% 
  bind_rows() %>% 
  gather(key = week, value = data, week_1:week_8) %>% 
  mutate(group = str_replace(group, ".csv", "")) %>% 
  separate(group, into = c("group", "id"), sep = "_") %>% 
  mutate(week = str_replace(week, "week_", ""))
```

### Spaghetti plot

Make a spaghetti plot showing observations on each subject over time, and comment on differences between groups.

``` r
study_data %>%
  ggplot(aes(x = as.numeric(week), y = data, color = id)) +
  geom_line() +
  facet_grid(~ group) +
  labs(
    title = "Observations on Each Subject over Time",
    x = "Week",
    y = "Value",
    caption = "Data from a longitudinal study") +
  theme(legend.position = "bottom")
```

![](p8105_hw5_zw2541_files/figure-markdown_github/unnamed-chunk-2-1.png)

Problem 2
---------

### Read and clean the data

``` r
homicides_data = 
  read.csv("./data_2/homicide-data.csv") %>% 
  janitor::clean_names() 
```

### Describe the raw data

Create a city\_state variable (e.g. "Baltimore, MD") and then summarize within cities to obtain the total number of homicides and the number of unsolved homicides (those for which the disposition is "Closed without arrest" or "Open/No arrest").

``` r
summarize_homicides = 
  homicides_data %>% 
  mutate(city_state = str_c(city, state, sep = ", ")) %>% 
  select(-city, -state) %>% 
  group_by(city_state) %>% 
  summarize(n_homicides = n(),
            n_unsolved_homicides = sum(disposition %in% c("Closed without arrest", "Open/No arrest")))

summarize_homicides
```

    ## # A tibble: 51 x 3
    ##    city_state      n_homicides n_unsolved_homicides
    ##    <chr>                 <int>                <int>
    ##  1 Albuquerque, NM         378                  146
    ##  2 Atlanta, GA             973                  373
    ##  3 Baltimore, MD          2827                 1825
    ##  4 Baton Rouge, LA         424                  196
    ##  5 Birmingham, AL          800                  347
    ##  6 Boston, MA              614                  310
    ##  7 Buffalo, NY             521                  319
    ##  8 Charlotte, NC           687                  206
    ##  9 Chicago, IL            5535                 4073
    ## 10 Cincinnati, OH          694                  309
    ## # ... with 41 more rows

### prop.test of Baltimore, MD

``` r
baltimore =
  summarize_homicides %>% 
  filter(city_state == "Baltimore, MD") 

  prop.test(baltimore$n_unsolved_homicides, baltimore$n_homicides) %>% 
    broom::tidy() %>% 
    select(estimate, conf.low, conf.high)
```

    ## # A tibble: 1 x 3
    ##   estimate conf.low conf.high
    ##      <dbl>    <dbl>     <dbl>
    ## 1    0.646    0.628     0.663

The estimated proportion is 0.646 and confidence intervals is (0.628, 0.663).
